# Generated by Django 5.2 on 2025-04-11 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='omani_id',
            field=models.CharField(blank=True, help_text='مثال: 1234567890123456', max_length=20, verbose_name='الهوية العمانية'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بالصيغة التالية: +968XXXXXXXX.', regex='^\\+968\\d{8}$')], verbose_name='رقم الهاتف'),
        ),
    ]
